# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download includes
        uses: actions/checkout@v2
        with:
          name: gemidyne/gh-actions-resources 
          repository: gemidyne/gh-actions-resources
          path: './ext'
          
        
      - uses: rumblefrog/setup-sp@master
        with:
         version: '1.10.x'
         
        
      - name: debug
        run: |
          ls
          
      - name: Copy morecolors
        run: |
          cp "./ext/sourcepawn/includes/morecolors.inc" "./include/morecolors.inc"
          
      - name: Copy tf_econ_data
        run: |
          cp "./ext/sourcepawn/includes/tf_econ_data.inc" "./include/tf_econ_data.inc"

      - name: Copy tf2attributes
        run: |
          cp "./ext/sourcepawn/includes/tf2attributes.inc" "./include/tf2attributes.inc"

      - name: Copy tf2items
        run: |
          cp "./ext/sourcepawn/includes/tf2items.inc" "./include/tf2items.inc"


      - run: spcomp './src/scripting/AS-MicroTF2.sp' -o './src/scripting/AS-MicroTF2.smx' -E
